### ISSUE TITLE
Any pretrained model available?

### ISSUE THREAD

**Issue by kkaiwwana** [bluffish/ubev#1]
Hi there. Thanks for you work.

I check those notebooks which look pretty simple to get started (that's exactly what I need: I'm in need of a bev perception model which accept multi-view camera inputs like NuScene and output BEV segmentation and, for segmentation it generated, I just need road semantics), though it's seems those pretrained weights are not available yet. 
So do you have any plan to release  those pretrained models ? Or could you provide any help (In a word, what I want is just a bev perception model for inference only)? Thanks in advance!

**Comment by bluffish** [comment]
Hello, do you still need it? I can give you one if you do.

**Comment by kkaiwwana** [comment]
Thank you for your help! However, I don't need that anymore since I eventually trained a CVT by myself.
